### PR TITLE
Added option for No cli input and calculated values

### PR DESCRIPTION
**Pull request by anjalijois**
Added option for no user input and extra_context in gw_recipe_pattern build function.
When no_input is True - User is not asked any questions and data is taken from cookiecutter.json file or as supplied by the user in extra_context.

### CODE REVIEW

**Comment by danwos** [comment]
Looks good, but error handling is missing.
What if no_input is not boolean or extra_context is not a dict?
You should catch this and throw an exception before cookiecutter gets these values. as input.

**Comment by danwos** [comment]
Ohh and please add some test cases. At least one for *no_input* and one for *extra_context*.

**Comment by anjalijois** [comment]
Sure Daniel.

**Comment by anjalijois** [comment]
Contains errors will send another pull request

**Pull request closed without merging**
